### PR TITLE
Use a radix tree instead of a hash table, to support in-order traversal

### PR DESCRIPTION
**Pull request by gvvaughan**
We're going to need a way to walk the sorted tree and track substrings to generate `isa_*.v80` from `tbl_*.v80`.  Since a radix tree does that and make a good replacement for a hash table, instead of bloating the code with both, let's switch to a radix tree for everything.

fix a couple of typos in tbl_z80.v80
    
    - add res2*hl' instead of double defining res2*hl
    - add sll*hl instead of double defining sl1*hl

improve help output from v80.c
    
    - and now that it's documented, make sure --quiet actually works!

reimplement symbol table with a radix tree
    
    - adjust symtab.c implementation to use radix.c
    - remove unused hash.c

abstract symbol table implementation properly
    
    - plug leaky abstraction of symbol table implemented as a hash
      table
    - outside of symtab.c, don't call any hash table apis
    - add new symtab apis that wrap previous hash table calls

new radix tree module
    
    - we can use this instead of the hash table in existing code
    - with a radix tree we'll also be able to do an in-order traversal
      to generate the v80 isa tables

### CODE REVIEW

**Comment by Kroc** [comment]
It didn't click that you don't just have push access, so I've added you as a collaborator so you can commit all you want.

**Comment by gvvaughan** [comment]
> It didn't click that you don't just have push access, so I've added you as a collaborator so you can commit all you want.

Cool, thank you!  I appreciate the vote of confidence 👍 

I think my inclination is actually to close this PR after our discussion in #4 .  Or perhaps to merge and then revert, since getting all the finicky radix tree code working was a good investment of time and that it would be nice to have that code in git somewhere on the off chance we ever have the need to dig it back out again.  WDYT @Kroc ?

**Comment by Kroc** [comment]
You should still keep it, I'm not opposed to it, I just need to think about how best to make this fit with the 8-bit version

**Comment by gvvaughan** [comment]
> It didn't click that you don't just have push access, so I've added you as a collaborator so you can commit all you want.

Screenshot 2024-10-04 at 9 39 13 AM

**Comment by Kroc** [comment]
Check your email, there should be an invite

image

**Pull request merged**
